
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'my_new_project'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

vars:
  snowplow_mobile:
    snowplow__atomic_schema: atomic
    snowplow__database: snowplow
    snowplow__enable_mobile_context: true
    snowplow__enable_geolocation_context: false
    snowplow__enable_application_context: true
    snowplow__enable_screen_context: true
    snowplow__enable_app_errors_module: false
    snowplow__start_date: '2022-08-01'
    snowplow__app_id: ['salesAndroidApp']
    
  snowplow_web:
    snowplow__atomic_schema: atomic
    snowplow__database: snowplow
    snowplow__enable_ua: true
    snowplow__enable_yauaa: true
    snowplow__start_date: '2022-09-15'
    snowplow__app_id: ['try-snowplow']
    snowplow__backfill_limit_days: 60
    
  snowplow_media_player:
    snowplow__percent_progress_boundaries: [20, 40, 60, 80]

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  my_new_project:
    models:
      snowplow_web:
        base:
          manifest:
            +schema: "snowplow_manifest"
          scratch:
            +schema: "scratch"
        page_views:
          +schema: "derived"
          scratch:
            +schema: "scratch"
        sessions:
          +schema: "derived"
          scratch:
            +schema: "scratch"
        user_mapping:
          +schema: "derived"
        users:
          +schema: "derived"
          scratch:
            +schema: "scratch"
